INSERT INTO USER_ACTION_LOG(id, user_id) VALUES(1, 10023);
INSERT INTO USER_ACTION_LOG(id, user_id) VALUES(2, 10024);
INSERT INTO USER_ACTION_LOG(id, user_id) VALUES(3, 10025);
INSERT INTO USER_ACTION_LOG(id, user_id) VALUES(4, 10026);

INSERT INTO SERVICE_ACCOUNT_LOG(id, user_action_log_id) VALUES (1, 3);
INSERT INTO SERVICE_ACCOUNT_LOG(id, user_action_log_id) VALUES (2, 3);

