spring.datasource:
  plarform: h2
  driverClassName: org.h2.Driver
  url: jdbc:h2:mem:mydb;DB_CLOSE_ON_EXIT=FALSE;MODE=MYSQL
#  url: jdbc:h2:tcp://localhost:9092/mem:testdb;MVCC=TRUE
  username: sa
  password:
  initialize: true # classpath:/schema.sql, import.sql, data.sql

  ## Pool Info ##
  maxActive: 100
  initialSize: 20
  minIdle: 20
  validationQuery: select 1
  testWhileIdle: true
  timeBetweenEvictionRunsMillis: 5000 #5 second
  minEvictableIdleTimeMillis: 10000   #10 second
  validationQueryTimeout: 5

spring.jpa:
  database: H2
  properties.hibernate.hbm2ddl.auto: create  # update, none, verify
  properties.hibernate.format_sql: true
  properties.hibernate.use_sql_comments: true