spring.datasource:
  plarform: h2
  driverClassName: org.h2.Driver
  url: jdbc:h2:mem:mydb;DB_CLOSE_ON_EXIT=FALSE;MODE=MYSQL
#  url: jdbc:h2:tcp://localhost:9092/mem:testdb;MVCC=TRUE
  username: sa
  password:

  ## Pool Info ##
  maxActive: 100
  initialSize: 20
  minIdle: 20
  validationQuery: select 1
  testWhileIdle: true
  timeBetweenEvictionRunsMillis: 5000 #5 second
  minEvictableIdleTimeMillis: 10000   #10 second
  validationQueryTimeout: 5